### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by loudoweb** [SlavaRa/fd-postfix-code-completion-plugin#14]
When I start flashdevelop 5, I have this error  : 

>Impossible de charger le type 'PluginCore.Utilities.SemVer' à partir de l'assembly 'PluginCore, >Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
>
>   à PostfixCodeCompletion.PluginMain.OnHaxeCompletionModeChanged()
 >  à PostfixCodeCompletion.PluginMain.HandleEvent(Object sender, NotifyEvent e, HandlingPriority >priority)
>   à PluginCore.Managers.EventManager.DispatchEvent(Object sender, NotifyEvent e)

translation: Could not load type 'PluginCore.Utilities.SemVer' from assembly 'PluginCore,

Other plugins work.

Any help? Thx

**Comment by SlavaRa** [comment]
What version of the FD?

**Comment by loudoweb** [comment]
FD 5.0.1.3 and last plugin.

It seems that the plugin works anyway. I just have this error every time I launch FlashDevelop.

**Comment by SlavaRa** [comment]
will be fixed today, sorry(

**Comment by SlavaRa** [comment]
FIxed.
Please use https://github.com/SlavaRa/fd-postfix-code-completion-plugin/raw/master/PostfixCodeCompletion-alpha-1.5.fdz

**Comment by loudoweb** [comment]
Great! Thank you.
