### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by ShockWave2048** [SlavaRa/fd-postfix-code-completion-plugin#2]
Вот такая ошибка при выборе пункта "sel"
(нужна хоть какая то инфа о том как применяется, а то примерно понял уже после того как автоматом посреди работы выпал список)

***************************************************************************************************
Подробная информация об использовании оперативной 
(JIT) отладки вместо данного диалогового 
окна содержится в конце этого сообщения.

************** Текст исключения **************
System.ArgumentOutOfRangeException: Длина не может быть меньше нуля.
Имя параметра: length
   в System.String.InternalSubStringWithChecks(Int32 startIndex, Int32 length, Boolean fAlwaysCopy)
   в PostfixCodeCompletion.PostfixCompletionItem.get_Description()
   в PluginCore.Controls.CompletionList.UpdateTip(Object sender, ElapsedEventArgs e)

************** Загруженные сборки **************
mscorlib
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
FlashDevelop
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/FlashDevelop.exe
----------------------------------------
PluginCore
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/PluginCore.DLL
----------------------------------------
System.Windows.Forms
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms.resources
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.4927 (NetFXspW7.050727-4900)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms.resources/2.0.0.0_ru_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
AirProperties
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/AirProperties.DLL
----------------------------------------
AS2Context
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/AS2Context.DLL
----------------------------------------
ASCompletion
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/ASCompletion.DLL
----------------------------------------
AS3Context
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/AS3Context.DLL
----------------------------------------
Aga
    Версия сборки: 1.7.0.0
    Версия Win32: 1.7.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Aga.DLL
----------------------------------------
XMLCompletion
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/XMLCompletion.DLL
----------------------------------------
ASClassWizard
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/ASClassWizard.DLL
----------------------------------------
BasicCompletion
    Версия сборки: 1.0.0.36205
    Версия Win32: 1.0.0.36205
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/BasicCompletion.DLL
----------------------------------------
BookmarkPanel
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/BookmarkPanel.DLL
----------------------------------------
BridgeSettings
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/BridgeSettings.DLL
----------------------------------------
CodeAnalyzer
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/CodeAnalyzer.DLL
----------------------------------------
CodeFormatter
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/CodeFormatter.DLL
----------------------------------------
Antlr3
    Версия сборки: 3.1.3.42154
    Версия Win32: 3.1.3.42154
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Antlr3.DLL
----------------------------------------
CodeRefactor
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/CodeRefactor.DLL
----------------------------------------
CssCompletion
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/CssCompletion.DLL
----------------------------------------
CustomizeToolbar
    Версия сборки: 1.0.1.0
    Версия Win32: 1.0.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/CustomizeToolbar.DLL
----------------------------------------
DataEncoder
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/DataEncoder.DLL
----------------------------------------
fdb.j4n
    Версия сборки: 0.0.0.0
    Версия Win32: 0.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/fdb.j4n.DLL
----------------------------------------
jni4net.n-0.8.4.0
    Версия сборки: 0.8.4.0
    Версия Win32: 0.8.4.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/jni4net.n-0.8.4.0.DLL
----------------------------------------
FileExplorer
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/FileExplorer.DLL
----------------------------------------
FlashConnect
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/FlashConnect.DLL
----------------------------------------
System.Configuration
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
FlashDebugger
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/FlashDebugger.DLL
----------------------------------------
FlashLogViewer
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/FlashLogViewer.DLL
----------------------------------------
FlashViewer
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/FlashViewer.DLL
----------------------------------------
HaXeContext
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/HaXeContext.DLL
----------------------------------------
jni4net.n.w32.v20-0.8.4.0
    Версия сборки: 0.8.4.0
    Версия Win32: 0.8.4.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/jni4net.n.w32.v20-0.8.4.0.DLL
----------------------------------------
LayoutManager
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/LayoutManager.DLL
----------------------------------------
System.Design
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Design/2.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
LoomContext
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/LoomContext.DLL
----------------------------------------
ProjectManager
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/ProjectManager.DLL
----------------------------------------
MacroManager
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/MacroManager.DLL
----------------------------------------
OutputPanel
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/OutputPanel.DLL
----------------------------------------
PHPContext
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/PHPContext.DLL
----------------------------------------
SwfOp
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/SwfOp.DLL
----------------------------------------
System.Runtime.Remoting
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Runtime.Remoting/2.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
ResultsPanel
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/ResultsPanel.DLL
----------------------------------------
SourceControl
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/SourceControl.DLL
----------------------------------------
StartPage
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/StartPage.DLL
----------------------------------------
System.Web
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.5459 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_32/System.Web/2.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
TaskListPanel
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/TaskListPanel.DLL
----------------------------------------
ATPlugin
    Версия сборки: 1.1.4819.14027
    Версия Win32: 1.1.4819.14027
    CodeBase: file:///C:/Users/Admin/AppData/Local/FlashDevelop/Plugins/ATPlugin.dll
----------------------------------------
ColtPlugin
    Версия сборки: 1.0.0.23721
    Версия Win32: 1.0.0.23721
    CodeBase: file:///C:/Users/Admin/AppData/Local/FlashDevelop/Plugins/ColtPlugin.dll
----------------------------------------
System.Web.Services
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Web.Services/2.0.0.0__b03f5f7f11d50a3a/System.Web.Services.dll
----------------------------------------
Jayrock.Json
    Версия сборки: 0.9.12915.0
    Версия Win32: 0.9.12915.0046
    CodeBase: file:///C:/Users/Admin/AppData/Local/FlashDevelop/Plugins/Jayrock.Json.dll
----------------------------------------
PostfixCodeCompletion
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Users/Admin/AppData/Local/FlashDevelop/Plugins/PostfixCodeCompletion.dll
----------------------------------------
xq3bc9mm
    Версия сборки: 1.0.0.0
    Версия Win32: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Версия сборки: 3.5.0.0
    Версия Win32: 3.5.30729.5420 built by: Win7SP1
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Core/3.5.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
xjnisbvg
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
mscorlib.resources
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
System.Drawing.Design
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.4927 (NetFXspW7.050727-4900)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing.Design/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.Design.dll
----------------------------------------
System.resources
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.resources/2.0.0.0_ru_b77a5c561934e089/System.resources.dll
----------------------------------------
net.sf.jni4net.jni.dynammic
    Версия сборки: 0.0.0.0
    Версия Win32: 0.8.4.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/jni4net.n-0.8.4.0.dll
----------------------------------------

************** Оперативная отладка (JIT) **************
Для подключения оперативной (JIT) отладки файл .config данного
приложения или компьютера (machine.config) должен иметь
значение jitDebugging, установленное в секции system.windows.forms.
Приложение также должно быть скомпилировано с включенной
отладкой.

Например:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

При включенной отладке JIT любое необрабатываемое исключение
пересылается отладчику JIT, зарегистрированному на данном компьютере,
вместо того чтобы обрабатываться данным диалоговым окном.

**Comment by SlavaRa** [comment]
С инфой как применяется и когда срабатывает, пока придется подождать((
Вы не могли бы прислать код на котором происходит ошибка?

**Comment by ShockWave2048** [comment]
В любом методе набираю переменную id (можно любую), появляется постфикс список и затем глючит, чаще всего с ошибкой фд, реже бывает молчит при выборе (раз было что случайно закоментил кусок класса)
если надо могу весь проект выложить, тока он под air sdk 17
```
package game.objects 
{
	import citrus.objects.NapePhysicsObject;
	import game.embed.Atlases;
	import citrus.objects.CitrusSprite;
	import flash.utils.setTimeout;
	import game.states.GameState;
	import nape.callbacks.CbType;
	import nape.geom.Vec2;
	import nape.phys.BodyType;
	import nape.shape.Circle;
	import nape.shape.Shape;
	import org.casalib.util.NumberUtil;
	import starling.core.Starling;
	import starling.display.Image;
	import starling.display.MovieClip;
	
	/**
	 * ...
	 * @author Roma Kraminskij - kraminskij@gmail.com
	 */
	public class Enemy extends NapePhysicsObject
	{
		static public const SIZE:Number = 100;
		
		public static var idCounter:uint = 0;
		static public var enemyttype:CbType = new CbType();
		
		public var id:uint = 0;
		
		public var dirX:Number = 3;
		
		public function Enemy(name:String, params:Object=null) 
		{
			id
			idCounter++;
			id = idCounter;
			
			super(name, params);
			
			var m:Image = new Image(Atlases.getAtlas("main_00").getTexture("enemy_00"));
			m.width = SIZE;
			m.height = SIZE;
			view = m;
			
			updateCallEnabled = true;
			
			setTimeout( timeShot, NumberUtil.randomIntegerWithinRange(2, 10) * 1000 );
		}
		
		private function timeShot():void 
		{
			if ( _ce.state is GameState) (_ce.state as GameState).shot(this);
			if ( !kill ) setTimeout( timeShot, NumberUtil.randomIntegerWithinRange(2, 10) * 1000 );
		}
		
		
		
		override public function update(timeDelta:Number):void 
		{
			super.update(timeDelta);
			body.position.x += dirX;
			if ( body.position.x >= 1024 ) dirX = -3;
			if ( body.position.x <= 0 ) dirX = 3;
		}
		/**
		 * 
		 * @param	a - this
		 * @param	b - bullet
		 */
		/*private function collideHandler(a:CitrusSprite, b:CitrusSprite, s:*, h:*):void 
		{
			kill = true;
		}*/
		
		override protected function createBody():void
		{
			super.createBody();
			body.type = BodyType.DYNAMIC;
			body.cbTypes.add( enemyttype );
		}
		
		override protected function createShape():void
		{
			body.shapes.clear();
			
			var s:Shape;
			
			s = new Circle( SIZE / 2.3 );
			body.shapes.add(s);
			
		}
		
		override protected function createFilter():void
		{
			super.createFilter();
		}
		
	}

}
```

**Comment by SlavaRa** [comment]
Спасибо, чуть позже займусь. Проект не надо.

**Comment by SlavaRa** [comment]
Проверь на последней версии, должно работать как надо, если все будет ок, то можно закрыть issue
