### ISSUE TITLE
Configuration option for leaving explicit type definitions to Haxe type inference?

### ISSUE THREAD

**Issue by cambiata** [SlavaRa/fd-postfix-code-completion-plugin#4]
It would be great with the possibility to turn of the generation of explicit type parameters.
Example
"var" completion on new Test(). would give
```
var test = new Test();
```
instead of 
```
var test:Test = new Test();
```

**Comment by Gama11** [comment]
That should probably even be the default for Haxe.

**Comment by SlavaRa** [comment]
Yes, WIP
